[package]
name = "viv_script"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.11", features = ["derive"] }
inkwell = { version = "0.2.0", features = ["llvm15-0"] }
thiserror = "1.0.41"
